import React from "react";

const Blogs = () => {
  return (
    <div className="container my-5">
      <h2>Difference between authorization and authentication</h2>
      <p>
        <b>Ans:</b> Authorization determines what the user can access and
        Authentication verifies the user.Authorization always takes place after
        authentication and Authentication is the first step of a good identity
        and access management process.Authorization isn’t visible to or
        changeable by the user and Authentication is visible to and partially
        changeable by the user.
      </p>
      <h2>
        Why are you using `firebase`? What other options do you have to
        implement authentication?
      </h2>
      <p>
        <b>Ans:</b> I use Firebase Authentication because building secure
        authentication systems are easy here.It also helping the sign-in and
        onboarding experience for end users.It provides supporting email and
        password accounts, phone auth, and Google, Twitter, Facebook, and GitHub
        login, and more.Other options i can have other than firebase are:
        <ul>
          <li>STYTCH</li>
          <li>Ory</li>
          <li>Supabase</li>
          <li>Octa</li>
          <li>Auth0</li>
        </ul>
      </p>
      <h2>
        What other services does `firebase` provide other than authentication?
      </h2>
      <p>
        <b>Ans:</b>The other services of Firebase are:
        <ul>
          <li>
            Cloud Storage: It allows us to store and manage various media
            content generated by mobile app users
          </li>
          <li>
            Google Analytics: It help us for tracking user demographics,
            behavior, purchasing patterns, revenue reports.
          </li>
          <li>Predictions: It helps to predict about product decisions.</li>
          <li>Cloud Messaging: It sends notification to mobiles.</li>
          <li>
            Dynamic Links: This used to generate deep links that redirect user
            traffic to landing page, website, or mobile applications.
          </li>
          <li>
            Remote Cofig: It helps in remotely changing your application UI and
            content, without publishing it again.
          </li>
        </ul>
      </p>
    </div>
  );
};

export default Blogs;
